language: python
python:
  - "3.6"
# command to install dependencies
addons:
  apt:
    packages:
      - google-chrome-stable
  firefox: latest
install:
  - make development
  # command to run tests
script:
  - make test
  - make test functional_tests
