language: python

python:
  - "3.5"
cache: pip
sudo: required 
notifications:
  webhooks:
    urls:  
  - https://iguana.ga:9000/hooks/build
    on_success: always
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
     
install:
  - make development

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  
script:
   - echo "asdffffffff"
#  - make test
#  - make test functional_tests
