language: python
python:
  - "3.6"
# command to install dependencies
sudo: required 
addons:
  chrome: stable
  firefox: latest
install:
  - make development
  # command to run tests
script:
  - xvfb-run make test
  - xvfb-run make test functional_tests
