language: python
python:
  - "3.5"
# command to install dependencies
cache: pip
sudo: required 
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
     
install:
  - make development

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  

  # command to run tests
script:
  #- xvfb-run make test
  - make test functional_tests
