language: python
python:
  - "3.5"
# command to install dependencies
cache: pip
sudo: required 
addons:
  chrome: stable
  firefox: latest
install:
  - make development
  # command to run tests
script:
  #- xvfb-run make test
  - xvfb-run make test functional_tests
