language: python

python:
  - "3.5"
notifications:
  webhooks:
    urls:  
      - https://iguana.ga:9000/build
    on_success: always
    
script:
   - echo "sdmfsdsffsdfdsdfs"
#  - make test
#  - make test functional_tests
